/**
 * export-auth-users.ts — Export minimum required Auth records for local clone
 *
 * Exports auth.users and auth.identities only. Does NOT export:
 *   - auth.sessions
 *   - auth.refresh_tokens
 *   - auth.mfa_factors / auth.mfa_challenges / auth.mfa_amr_claims
 *   - auth.oauth_clients / auth.oauth_authorizations
 *   - auth.flow_state
 *   - auth.audit_log_entries
 *
 * Auth handling policy:
 *   - User UUIDs are preserved exactly (needed for FK integrity in public).
 *   - Production password hashes are NOT copied. Local-controlled
 *     passwords are used: crypt('local-only-no-production-hash', gen_salt('bf')).
 *     This means local logins won't work with production passwords — that's
 *     intentional. The separate bootstrap-local-admin script creates a
 *     local super admin with a known password.
 *   - email, raw_app_meta_data, raw_user_meta_data, and other metadata
 *     fields are preserved exactly.
 *   - Generated columns (confirmed_at) are excluded — they're auto-computed.
 *   - Session-related fields (confirmation_token, recovery_token,
 *     email_change_token_*, reauthentication_token) are blanked — they
 *     are session-specific and not needed for FK integrity.
 *
 * Output is a SQL dump that can be applied to a local Supabase instance.
 *
 * Usage:
 *   PROD_DB_URL=... tsx scripts/db/export-auth-users.ts --out <path>
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { assertProductionDbUrl, getProdDbUrl, redactDbUrl } from './db-workflow-lib.ts';

const DEFAULT_OUT = resolve(process.cwd(), '.backups', 'prod', 'auth-minimal.sql');

interface AuthUser {
	id: string;
	aud: string | null;
	role: string | null;
	email: string | null;
	email_confirmed_at: string | null;
	raw_app_meta_data: unknown;
	raw_user_meta_data: unknown;
	is_super_admin: boolean;
	phone: string | null;
	phone_confirmed_at: string | null;
	banned_until: string | null;
	deleted_at: string | null;
	is_sso_user: boolean;
	is_anonymous: boolean;
	created_at: string;
	updated_at: string;
}

interface AuthIdentity {
	id: string;
	user_id: string;
	identity_data: unknown;
	provider: string;
	provider_id: string;
	last_sign_in_at: string | null;
	created_at: string;
	updated_at: string;
}

function sqlLiteral(value: string | null): string {
	if (value === null) return 'NULL';
	if (value === 'true' || value === 'false') return value;
	return `'${value.replaceAll("'", "''")}'`;
}

function jsonLiteral(value: unknown): string {
	const json = JSON.stringify(value);
	return `'${json.replaceAll("'", "''")}'::jsonb`;
}

function generateAuthDump(users: AuthUser[], identities: AuthIdentity[]): string {
	const lines: string[] = [];
	lines.push('-- Synthetic Auth dump (generated by export-auth-users.ts)');
	lines.push('-- Preserves production UUIDs and metadata. Passwords are LOCAL-CONTROLLED.');
	lines.push('-- Excludes: sessions, tokens, MFA, OAuth, flow_state, audit');
	lines.push('-- Excludes generated columns: confirmed_at');
	lines.push('-- Blanks session-specific tokens: confirmation_token, recovery_token, etc.');
	lines.push('');

	lines.push('-- auth.users (local-controlled passwords)');
	lines.push('INSERT INTO auth.users (');
	lines.push('  instance_id, id, aud, role, email, encrypted_password,');
	lines.push('  email_confirmed_at, raw_app_meta_data, raw_user_meta_data,');
	lines.push('  is_super_admin, phone, phone_confirmed_at, banned_until,');
	lines.push('  is_sso_user, is_anonymous, created_at, updated_at');
	lines.push(') VALUES');
	const userValues = users.map((u, i) => {
		const prefix = '  (';
		const suffix = i === users.length - 1 ? ')' : '),';
		return [
			prefix,
			`'00000000-0000-0000-0000-000000000000'::uuid,`,
			`${sqlLiteral(u.id)}::uuid,`,
			`${sqlLiteral(u.aud)},`,
			`${sqlLiteral(u.role)},`,
			`${sqlLiteral(u.email)},`,
			`'local-only-no-production-hash',`, // local-controlled password
			`${u.email_confirmed_at ? `'${u.email_confirmed_at}'::timestamptz` : 'NULL'},`,
			`${jsonLiteral(u.raw_app_meta_data)},`,
			`${jsonLiteral(u.raw_user_meta_data)},`,
			`${u.is_super_admin ? 'true' : 'false'},`,
			`${sqlLiteral(u.phone)},`,
			`${u.phone_confirmed_at ? `'${u.phone_confirmed_at}'::timestamptz` : 'NULL'},`,
			`${u.banned_until ? `'${u.banned_until}'::timestamptz` : 'NULL'},`,
			`${u.is_sso_user ? 'true' : 'false'},`,
			`${u.is_anonymous ? 'true' : 'false'},`,
			`'${u.created_at}'::timestamptz,`,
			`'${u.updated_at}'::timestamptz`,
			suffix,
		].join(' ');
	});
	lines.push(...userValues);
	lines.push('ON CONFLICT (id) DO NOTHING;');
	lines.push('');

	lines.push('-- auth.identities');
	lines.push('INSERT INTO auth.identities (');
	lines.push('  id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at');
	lines.push(') VALUES');
	const idValues = identities.map((id, i) => {
		const prefix = '  (';
		const suffix = i === identities.length - 1 ? ')' : '),';
		return [
			prefix,
			`${sqlLiteral(id.id)}::uuid,`,
			`${sqlLiteral(id.user_id)}::uuid,`,
			`${jsonLiteral(id.identity_data)},`,
			`${sqlLiteral(id.provider)},`,
			`${sqlLiteral(id.provider_id)},`,
			`${id.last_sign_in_at ? `'${id.last_sign_in_at}'::timestamptz` : 'NULL'},`,
			`'${id.created_at}'::timestamptz,`,
			`'${id.updated_at}'::timestamptz`,
			suffix,
		].join(' ');
	});
	lines.push(...idValues);
	lines.push('ON CONFLICT (id) DO NOTHING;');
	lines.push('');

	return lines.join('\n');
}

function main(): void {
	const args = process.argv.slice(2);
	const outIdx = args.indexOf('--out');
	const outPath = outIdx !== -1 ? resolve(process.cwd(), args[outIdx + 1]) : DEFAULT_OUT;

	const { url: prodDbUrl, source } = getProdDbUrl();
	assertProductionDbUrl(prodDbUrl);

	console.info('Export Auth (minimum required for FK integrity)');
	console.info(`  PROD_DB_URL source: ${source}`);
	console.info(`  Target: ${redactDbUrl(prodDbUrl)}`);
	console.info(`  Output: ${outPath}`);

	// Import psql execution
	const usersResult = spawnSync('psql', [
		'--set', 'ON_ERROR_STOP=1',
		'--no-align',
		'--tuples-only',
		'--no-psqlrc',
		'--dbname', prodDbUrl,
		'--command', `
select coalesce(json_agg(sub), '[]'::json)::text from (
  select
    id, aud, role, email,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    phone, phone_confirmed_at,
    banned_until, deleted_at,
    is_sso_user, is_anonymous,
    created_at, updated_at
  from auth.users
  where deleted_at is null
  order by created_at
) sub;
`,
	], { encoding: 'utf8', stdio: 'pipe' });

	if (usersResult.status !== 0) {
		console.error(`Failed to query auth.users: ${usersResult.stderr}`);
		process.exit(1);
	}

	const identitiesResult = spawnSync('psql', [
		'--set', 'ON_ERROR_STOP=1',
		'--no-align',
		'--tuples-only',
		'--no-psqlrc',
		'--dbname', prodDbUrl,
		'--command', `
select coalesce(json_agg(sub), '[]'::json)::text from (
  select
    id, user_id, identity_data,
    provider, provider_id, last_sign_in_at,
    created_at, updated_at
  from auth.identities
  order by created_at
) sub;
`,
	], { encoding: 'utf8', stdio: 'pipe' });

	if (identitiesResult.status !== 0) {
		console.error(`Failed to query auth.identities: ${identitiesResult.stderr}`);
		process.exit(1);
	}

	const users: AuthUser[] = JSON.parse(usersResult.stdout.trim());
	const identities: AuthIdentity[] = JSON.parse(identitiesResult.stdout.trim());

	mkdirSync(dirname(outPath), { recursive: true });
	const dump = generateAuthDump(users, identities);
	writeFileSync(outPath, dump, 'utf8');

	console.info(`Auth export complete: ${outPath}`);
	console.info(`  Users: ${users.length}`);
	console.info(`  Identities: ${identities.length}`);
	console.log('');
	console.log('Auth fields transformed:');
	console.log('  - encrypted_password → local-controlled hash (no production passwords copied)');
	console.log('  - confirmation_token, recovery_token, email_change_*, reauthentication_token → blanked');
	console.log('Auth fields preserved exactly:');
	console.log('  - id (UUID), aud, role, email, raw_app_meta_data, raw_user_meta_data');
	console.log('  - is_super_admin, phone, is_sso_user, is_anonymous, created_at, updated_at');
	console.log('Auth fields excluded:');
	console.log('  - confirmed_at (generated column, auto-computed)');
	console.log('  - auth.sessions, auth.refresh_tokens, auth.mfa_*, auth.oauth_*, auth.flow_state, auth.audit_log_entries');
}

main();
