/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/celebra-memories-retrieve/wrangler.json --include-runtime=false --env-interface=MemoriesRetrieveBindings workers/celebra-memories-retrieve/worker-bindings.d.ts` (hash: 0f288ed371e228940c8db295fad96a33)
interface __BaseEnv_MemoriesRetrieveBindings {
	MEMORIES_BUCKET: R2Bucket;
	NONCE_GUARD: DurableObjectNamespace;
	MEMORIES_STORAGE_TARGET: "local" | "staging" | "production";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface LocalEnv {
	MEMORIES_BUCKET: R2Bucket;
	NONCE_GUARD: DurableObjectNamespace;
		MEMORIES_STORAGE_TARGET: "local";
	}
	interface StagingEnv {
	MEMORIES_BUCKET: R2Bucket;
	NONCE_GUARD: DurableObjectNamespace;
	MEMORIES_STORAGE_TARGET: "staging";
}
	interface Env extends __BaseEnv_MemoriesRetrieveBindings {}
}
interface MemoriesRetrieveBindings extends __BaseEnv_MemoriesRetrieveBindings {}
// NodeJS.ProcessEnv projection removed: this monorepo validates partial script environments.
