// src/core/errors/errorCodes.ts

/**
 * Enum for standardizing error codes throughout the application.
 */
export enum ErrorCodes {
	BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
	REPOSITORY_ERROR = 'REPOSITORY_ERROR',
	EMAIL_SERVICE_ERROR = 'EMAIL_SERVICE_ERROR',
	CONTROLLER_ERROR = 'CONTROLLER_ERROR',
	CLIENT_IP_ERROR = 'CLIENT_IP_ERROR',
	DATA_SANITIZATION_ERROR = 'DATA_SANITIZATION_ERROR',
	CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
	INITIALIZATION_ERROR = 'INITIALIZATION_ERROR',
	UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
}
