import type { IntakeBlockDefinition } from '@/lib/intake/types';

export const dateLocationsBlock: IntakeBlockDefinition = {
	type: 'date-locations',
	displayName: 'Fecha y ubicaciones',
	description: 'Ceremonia, recepción, direcciones y códigos de vestimenta.',
	supportedEventTypes: ['xv', 'boda', 'bautizo', 'cumple', 'baby-shower'],
	fields: [
		{
			name: 'ceremonyVenueName',
			label: 'Nombre del lugar de ceremonia (opcional)',
			type: 'text',
			required: false,
			placeholder: 'Ej: Parroquia del Sagrado Corazón',
		},
		{
			name: 'ceremonyAddress',
			label: 'Dirección de la ceremonia',
			type: 'text',
			required: false,
			placeholder: 'Ej: Av. de las Rosas 240, Querétaro',
		},
		{
			name: 'ceremonyCity',
			label: 'Ciudad de la ceremonia',
			type: 'text',
			required: false,
			placeholder: 'Ej: Querétaro',
		},
		{
			name: 'ceremonyDate',
			label: 'Fecha de la ceremonia (texto)',
			type: 'text',
			required: false,
			placeholder: 'Ej: 20 de noviembre de 2027',
		},
		{
			name: 'ceremonyTime',
			label: 'Hora de la ceremonia',
			type: 'text',
			required: false,
			placeholder: 'Ej: 6:00 PM',
		},
		{
			name: 'ceremonyMapUrl',
			label: 'Enlace de Google Maps — ceremonia (opcional)',
			type: 'url',
			required: false,
		},
		{
			name: 'receptionVenueName',
			label: 'Nombre del lugar de recepción (opcional)',
			type: 'text',
			required: false,
			placeholder: 'Ej: Salón Imperial',
		},
		{
			name: 'receptionAddress',
			label: 'Dirección de la recepción',
			type: 'text',
			required: false,
			placeholder: 'Ej: Paseo del Palacio 18, Querétaro',
		},
		{
			name: 'receptionCity',
			label: 'Ciudad de la recepción',
			type: 'text',
			required: false,
			placeholder: 'Ej: Querétaro',
		},
		{
			name: 'receptionDate',
			label: 'Fecha de la recepción (texto)',
			type: 'text',
			required: false,
			placeholder: 'Ej: 20 de noviembre de 2027',
		},
		{
			name: 'receptionTime',
			label: 'Hora de la recepción',
			type: 'text',
			required: false,
			placeholder: 'Ej: 8:00 PM',
		},
		{
			name: 'receptionMapUrl',
			label: 'Enlace de Google Maps — recepción (opcional)',
			type: 'url',
			required: false,
		},
		{
			name: 'dressCode',
			label: 'Código de vestimenta (opcional)',
			type: 'text',
			required: false,
			placeholder: 'Ej: Formal de gala. Rosa satín reservado para la quinceañera.',
		},
		{
			name: 'additionalIndications',
			label: 'Indicaciones adicionales (opcional)',
			type: 'textarea',
			required: false,
			placeholder: 'Cualquier otra indicación para los invitados.',
		},
	],
};
