/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/celebra-memories-sign/wrangler.json --include-runtime=false --env-interface=MemoriesSignBindings workers/celebra-memories-sign/worker-bindings.d.ts` (hash: a5dfdf68dcba2c46278d82c1ae70c517)
interface __BaseEnv_MemoriesSignBindings {
	SIGN_RATE_LIMITER: RateLimit;
	MEMORIES_BUCKET: R2Bucket;
	NONCE_GUARD: DurableObjectNamespace;
	MEMORIES_STORAGE_TARGET: "local" | "staging" | "production";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface LocalEnv {
	SIGN_RATE_LIMITER: RateLimit;
	MEMORIES_BUCKET: R2Bucket;
	NONCE_GUARD: DurableObjectNamespace;
		MEMORIES_STORAGE_TARGET: "local";
	}
	interface StagingEnv {
	SIGN_RATE_LIMITER: RateLimit;
	MEMORIES_BUCKET: R2Bucket;
	NONCE_GUARD: DurableObjectNamespace;
	MEMORIES_STORAGE_TARGET: "staging";
}
	interface Env extends __BaseEnv_MemoriesSignBindings {}
}
interface MemoriesSignBindings extends __BaseEnv_MemoriesSignBindings {}
// NodeJS.ProcessEnv projection removed: this monorepo validates partial script environments.
