/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/celebra-memories-sign/wrangler.json --include-runtime=false --env-interface=MemoriesSignBindings workers/celebra-memories-sign/worker-bindings.d.ts` (hash: 7c1f2d0e9b4a6c3d8e5f1a2b3c4d5e6f)
interface __BaseEnv_MemoriesSignBindings {
	SIGN_RATE_LIMITER: RateLimit;
	MEMORIES_BUCKET: R2Bucket;
	NONCE_GUARD: DurableObjectNamespace;
	MEMORIES_STORAGE_TARGET: 'local' | 'staging' | 'production';
	MEMORIES_ALLOWED_ORIGINS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import('./src/index');
	}
	interface LocalEnv {
		SIGN_RATE_LIMITER: RateLimit;
		MEMORIES_BUCKET: R2Bucket;
		NONCE_GUARD: DurableObjectNamespace;
		MEMORIES_STORAGE_TARGET: 'local';
		MEMORIES_ALLOWED_ORIGINS: 'http://localhost:4321,http://127.0.0.1:4321';
	}
	interface StagingEnv {
		SIGN_RATE_LIMITER: RateLimit;
		MEMORIES_BUCKET: R2Bucket;
		NONCE_GUARD: DurableObjectNamespace;
		MEMORIES_STORAGE_TARGET: 'staging';
		MEMORIES_ALLOWED_ORIGINS: 'https://celebra-me.vercel.app';
	}
	interface Env extends __BaseEnv_MemoriesSignBindings {}
}
interface MemoriesSignBindings extends __BaseEnv_MemoriesSignBindings {}
// NodeJS.ProcessEnv projection removed: this monorepo validates partial script environments.
