import type { DemoPreset } from '@/lib/intake/types';

const ALL_MVP_BLOCKS = [
	'event-details',
	'main-people',
	'date-locations',
	'photos',
	'rsvp-config',
	'music',
	'gifts',
	'special-messages',
] as const;

const DEFAULT_SECTIONS = [
	'quote',
	'family',
	'gallery',
	'countdown',
	'location',
	'itinerary',
	'rsvp',
	'gifts',
	'thankYou',
] as const;

const COMMON_REQUIRED_ASSETS = ['hero', 'portrait'] as const;

export const DEMO_PRESET_CATALOG: readonly DemoPreset[] = [
	{
		id: 'demo-xv-jewelry-box',
		eventType: 'xv',
		displayName: 'XV Años — Jewelry Box',
		themeId: 'jewelry-box',
		defaultSections: [...DEFAULT_SECTIONS],
		supportedBlocks: [...ALL_MVP_BLOCKS],
		recommendedBlocks: [
			'event-details',
			'main-people',
			'date-locations',
			'photos',
			'rsvp-config',
			'gifts',
			'special-messages',
		],
		requiredAssets: [...COMMON_REQUIRED_ASSETS, 'gallery01', 'gallery02', 'gallery03'],
		previewSlug: 'demo-xv-jewelry-box',
	},
	{
		id: 'demo-xv-editorial',
		eventType: 'xv',
		displayName: 'XV Años — Editorial',
		themeId: 'editorial',
		defaultSections: [...DEFAULT_SECTIONS],
		supportedBlocks: [...ALL_MVP_BLOCKS],
		recommendedBlocks: [
			'event-details',
			'main-people',
			'date-locations',
			'photos',
			'rsvp-config',
			'music',
			'gifts',
			'special-messages',
		],
		requiredAssets: [...COMMON_REQUIRED_ASSETS, 'gallery01', 'gallery02', 'gallery03'],
		previewSlug: 'demo-xv-editorial',
	},
	{
		id: 'demo-xv-enchanted-rose',
		eventType: 'xv',
		displayName: 'XV Años — Enchanted Rose',
		themeId: 'enchanted-rose',
		defaultSections: [
			'quote',
			'location',
			'countdown',
			'family',
			'itinerary',
			'gallery',
			'gifts',
			'rsvp',
			'thankYou',
		],
		supportedBlocks: [...ALL_MVP_BLOCKS],
		recommendedBlocks: [
			'event-details',
			'main-people',
			'date-locations',
			'photos',
			'rsvp-config',
			'music',
			'gifts',
			'special-messages',
		],
		requiredAssets: [
			...COMMON_REQUIRED_ASSETS,
			'gallery01',
			'gallery02',
			'gallery03',
			'interlude01',
			'interlude02',
		],
		previewSlug: 'demo-xv-enchanted-rose',
	},
	{
		id: 'demo-xv-celestial-blue',
		eventType: 'xv',
		displayName: 'XV Años — Celestial Blue',
		themeId: 'celestial-blue',
		defaultSections: [...DEFAULT_SECTIONS],
		supportedBlocks: [...ALL_MVP_BLOCKS],
		recommendedBlocks: [
			'event-details',
			'main-people',
			'date-locations',
			'photos',
			'rsvp-config',
			'music',
			'gifts',
			'special-messages',
		],
		requiredAssets: [...COMMON_REQUIRED_ASSETS, 'gallery01', 'gallery02', 'gallery03'],
		previewSlug: 'demo-xv-celestial-blue',
	},
	{
		id: 'demo-boda-jewelry-box-wedding',
		eventType: 'boda',
		displayName: 'Boda — Jewelry Box Wedding',
		themeId: 'jewelry-box-wedding',
		defaultSections: [...DEFAULT_SECTIONS],
		supportedBlocks: [...ALL_MVP_BLOCKS],
		recommendedBlocks: [
			'event-details',
			'main-people',
			'date-locations',
			'photos',
			'rsvp-config',
			'music',
			'gifts',
			'special-messages',
		],
		requiredAssets: [...COMMON_REQUIRED_ASSETS, 'gallery01', 'gallery02', 'gallery03'],
		previewSlug: 'demo-boda-jewelry-box-wedding',
	},
	{
		id: 'demo-bautismo-angelic-presence',
		eventType: 'bautizo',
		displayName: 'Bautizo — Angelic Presence',
		themeId: 'angelic-presence',
		defaultSections: [...DEFAULT_SECTIONS],
		supportedBlocks: [...ALL_MVP_BLOCKS],
		recommendedBlocks: [
			'event-details',
			'main-people',
			'date-locations',
			'photos',
			'rsvp-config',
			'gifts',
			'special-messages',
		],
		requiredAssets: [...COMMON_REQUIRED_ASSETS, 'gallery01', 'gallery02'],
		previewSlug: 'demo-bautismo-angelic-presence',
	},
	{
		id: 'demo-cumple-luxury-hacienda',
		eventType: 'cumple',
		displayName: 'Cumpleaños — Luxury Hacienda',
		themeId: 'luxury-hacienda',
		defaultSections: [...DEFAULT_SECTIONS],
		supportedBlocks: [...ALL_MVP_BLOCKS],
		recommendedBlocks: [
			'event-details',
			'date-locations',
			'photos',
			'rsvp-config',
			'music',
			'gifts',
			'special-messages',
		],
		requiredAssets: [...COMMON_REQUIRED_ASSETS, 'gallery01', 'gallery02'],
		previewSlug: 'demo-cumple-luxury-hacienda',
	},
	{
		id: 'demo-baby-shower-celestial',
		eventType: 'baby-shower',
		displayName: 'Baby Shower — Celestial Demo',
		themeId: 'celestial-blue',
		defaultSections: ['quote', 'family', 'gallery', 'location', 'gifts', 'rsvp', 'thankYou'],
		supportedBlocks: [...ALL_MVP_BLOCKS],
		recommendedBlocks: [
			'event-details',
			'main-people',
			'date-locations',
			'photos',
			'rsvp-config',
			'gifts',
			'special-messages',
		],
		requiredAssets: ['hero', 'family', 'gallery01'],
		previewSlug: 'demo-baby-shower-celestial',
	},
] as const;

export function findDemoPreset(id: string): DemoPreset | undefined {
	return DEMO_PRESET_CATALOG.find((preset) => preset.id === id);
}

export function findDemoPresetsByEventType(eventType: string): DemoPreset[] {
	return DEMO_PRESET_CATALOG.filter((preset) => preset.eventType === eventType);
}
