-- ============================================================================
-- Romina Ríos Chaparro — XV invitation preparation patch
-- Generated by scripts/dev/generate-romina-invitation-sql.ts from the typed
-- canonical source scripts/dev/romina-invitation-data.ts. Do not hand-edit.
--
-- PENDING_DIRECT_CEREMONY_MAP_URL: current search URL is retained.
-- PENDING_DIRECT_RECEPTION_MAP_URL: current search URL is retained.
-- PENDING_RECEPTION_TIMELINE_CONFIRMATION: provisional itinerary is retained.
-- PENDING_MUSIC_AUDIO_ASSET, PENDING_RSVP_DEADLINE,
-- PENDING_RSVP_ACCESS_MODE_CONFIRMATION, PENDING_GUEST_LIST,
-- PENDING_DRESS_CODE, PENDING_GIFT_REGISTRY, PENDING_CHILDREN_POLICY,
-- PENDING_HASHTAG: optional fields are intentionally omitted.
-- PENDING_PRESENTATION_COPY and PENDING_CLOSING_COPY: provisional approved-safe
-- copy is retained in the canonical typed source.
--
-- REQUIRED BEFORE EXECUTION:
-- 1. Create this client invitation and upload the eleven canonical images via
--    the dashboard/asset workflow; this patch does not upload Storage objects.
-- 2. Replace __OWNER_USER_ID__ and __SUPABASE_PROJECT_URL__.
-- 3. Take a verified backup, validate this generated file, and obtain approval.
-- ============================================================================
-- @script-id: 20260716_prepare_romina_rios_chaparro_xv
-- @purpose: Prepare the published Romina Ríos Chaparro XV invitation from canonical typed content and existing normalized Storage assets
-- @env: production
-- @ticket: Romina invitation preparation; source scripts/dev/romina-invitation-data.ts
-- @tables: public.invitations, public.invitation_assets, public.published_invitation_content, public.events, public.event_memberships
-- @operation: update
-- @expected-rows-min: 1
-- @expected-rows-max: 5
-- @requires-backup: true
-- @dry-run-query: SELECT id, slug, event_type, status, base_demo_id, theme_id, archived_at FROM public.invitations WHERE slug = 'romina-rios-chaparro' AND event_type = 'xv'; SELECT id, display_name, bucket, storage_path, deleted_at FROM public.invitation_assets WHERE invitation_id = (SELECT id FROM public.invitations WHERE slug = 'romina-rios-chaparro' AND event_type = 'xv' AND archived_at IS NULL); SELECT id, slug, event_type, version, published_at, deleted_at FROM public.published_invitation_content WHERE slug = 'romina-rios-chaparro' AND event_type = 'xv'; SELECT id, slug, event_type, status, invitation_project_id, deleted_at FROM public.events WHERE slug = 'romina-rios-chaparro';
-- @rollback: Restore the verified backup or archive the invitation through the approved application workflow; never delete guest or Storage history manually.

BEGIN;

SELECT set_config('app.owner_user_id', '__OWNER_USER_ID__', true);
SELECT set_config('app.storage_public_url', '__SUPABASE_PROJECT_URL__', true);

DO $romina$
DECLARE
  v_invitation_id uuid;
  v_owner_id uuid;
  v_event_id uuid;
  v_content jsonb;
  v_content_text text := $romina_content$
{
  "eventType": "xv",
  "isDemo": false,
  "templateId": "xv-premiere-floral",
  "visualProfileId": "romina-rios-chaparro",
  "title": "XV años de Romina Ríos Chaparro",
  "description": "Acompáñeme a celebrar este momento tan especial.",
  "theme": {
    "preset": "premiere-floral"
  },
  "eventTiming": {
    "localDateTime": "2026-08-14T17:00",
    "timeZone": "America/Chihuahua",
    "startsAtUtc": "2026-08-14T23:00:00.000Z"
  },
  "sectionOrder": [
    "quote",
    "family",
    "countdown",
    "location",
    "itinerary",
    "gallery",
    "personalizedAccess",
    "rsvp",
    "thankYou"
  ],
  "_assetSlug": "romina-rios-chaparro",
  "hero": {
    "name": "Romina Ríos Chaparro",
    "label": "Mis XV",
    "date": "2026-08-14T23:00:00.000Z",
    "backgroundImage": {
      "type": "uploaded",
      "assetId": "__ROMINA_ASSET_ID_hero__",
      "src": "__ROMINA_ASSET_URL_hero__"
    },
    "backgroundImageMobile": {
      "type": "uploaded",
      "assetId": "__ROMINA_ASSET_ID_hero__",
      "src": "__ROMINA_ASSET_URL_hero__"
    },
    "backgroundImageDesktop": {
      "type": "uploaded",
      "assetId": "__ROMINA_ASSET_ID_hero__",
      "src": "__ROMINA_ASSET_URL_hero__"
    },
    "portrait": {
      "type": "uploaded",
      "assetId": "__ROMINA_ASSET_ID_portrait__",
      "src": "__ROMINA_ASSET_URL_portrait__"
    },
    "focalPoint": "50% 42%",
    "focalPointMobile": "50% 42%",
    "focalPointTablet": "50% 40%",
    "focalPointDesktop": "58% 46%"
  },
  "envelope": {
    "disabled": false,
    "cardLabel": "Mis XV",
    "envelopeName": "Romina",
    "cardName": "Romina",
    "cardTagline": "14 · 08 · 2026",
    "sealStyle": "wax",
    "sealIcon": "monogram",
    "sealInitials": "R",
    "microcopy": "Abra su invitación",
    "closedPalette": {
      "primary": "surfacePrimary",
      "accent": "actionAccent",
      "background": "surfaceDark"
    }
  },
  "quote": {
    "text": "Hay momentos que se sueñan toda la vida. Me hará muy feliz compartir con usted la celebración de mis XV años.",
    "author": "Romina"
  },
  "family": {
    "parents": {
      "mother": "Claudia Chaparro Juárez",
      "father": "Christian Miguel Ríos"
    },
    "parentsOrder": "mother-first",
    "godparents": [
      {
        "name": "Fernando Nájera"
      },
      {
        "name": "Esmeralda Carbajal"
      }
    ],
    "labels": {
      "sectionTitle": "Mi familia",
      "parentsTitle": "Con el amor de mis padres",
      "godparentsTitle": "Acompañada por mis padrinos"
    },
    "featuredImage": {
      "type": "uploaded",
      "assetId": "__ROMINA_ASSET_ID_family__",
      "src": "__ROMINA_ASSET_URL_family__"
    },
    "focalPoint": "50% 35%"
  },
  "countdown": {
    "title": "La celebración comienza en",
    "footerText": "Ceremonia · 5:00 p. m."
  },
  "location": {
    "visibility": "public",
    "introEyebrow": "14 de agosto de 2026",
    "introHeading": "Ceremonia y recepción",
    "ceremony": {
      "venueEvent": "Ceremonia",
      "venueName": "Catedral de Nuestra Señora de la Medalla Milagrosa",
      "address": "Boulevard Benito Juárez #200, Col. Centro, C.P. 31700, Nuevo Casas Grandes, Chihuahua",
      "city": "Nuevo Casas Grandes, Chihuahua",
      "date": "14 de agosto de 2026",
      "time": "5:00 p. m.",
      "mapUrl": "https://www.google.com/maps/search/?api=1&query=Catedral%20de%20Nuestra%20Se%C3%B1ora%20de%20la%20Medalla%20Milagrosa%2C%20Boulevard%20Benito%20Ju%C3%A1rez%20%23200%2C%20Col.%20Centro%2C%20C.P.%2031700%2C%20Nuevo%20Casas%20Grandes%2C%20Chihuahua",
      "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Catedral%20de%20Nuestra%20Se%C3%B1ora%20de%20la%20Medalla%20Milagrosa%2C%20Boulevard%20Benito%20Ju%C3%A1rez%20%23200%2C%20Col.%20Centro%2C%20C.P.%2031700%2C%20Nuevo%20Casas%20Grandes%2C%20Chihuahua",
      "appleMapsUrl": "https://maps.apple.com/?q=Catedral%20de%20Nuestra%20Se%C3%B1ora%20de%20la%20Medalla%20Milagrosa%2C%20Boulevard%20Benito%20Ju%C3%A1rez%20%23200%2C%20Col.%20Centro%2C%20C.P.%2031700%2C%20Nuevo%20Casas%20Grandes%2C%20Chihuahua"
    },
    "reception": {
      "venueEvent": "Recepción",
      "venueName": "Gabro Jardín de Eventos",
      "address": "Libramiento Gómez Morín, C.P. 31805, Nuevo Casas Grandes, Chihuahua",
      "city": "Nuevo Casas Grandes, Chihuahua",
      "date": "14 de agosto de 2026",
      "time": "Cena a partir de las 8:30 p. m.",
      "mapUrl": "https://www.google.com/maps/search/?api=1&query=Gabro%20Jard%C3%ADn%20de%20Eventos%2C%20Libramiento%20G%C3%B3mez%20Mor%C3%ADn%2C%20C.P.%2031805%2C%20Nuevo%20Casas%20Grandes%2C%20Chihuahua",
      "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Gabro%20Jard%C3%ADn%20de%20Eventos%2C%20Libramiento%20G%C3%B3mez%20Mor%C3%ADn%2C%20C.P.%2031805%2C%20Nuevo%20Casas%20Grandes%2C%20Chihuahua",
      "appleMapsUrl": "https://maps.apple.com/?q=Gabro%20Jard%C3%ADn%20de%20Eventos%2C%20Libramiento%20G%C3%B3mez%20Mor%C3%ADn%2C%20C.P.%2031805%2C%20Nuevo%20Casas%20Grandes%2C%20Chihuahua"
    }
  },
  "interludes": [
    {
      "image": {
        "type": "uploaded",
        "assetId": "__ROMINA_ASSET_ID_sageLandscape__",
        "src": "__ROMINA_ASSET_URL_sageLandscape__"
      },
      "afterSection": "location",
      "alt": "Romina con vestido verde salvia en un jardín botánico",
      "height": "tall",
      "focalPoint": "50% 42%"
    }
  ],
  "itinerary": {
    "title": "Programa",
    "items": [
      {
        "time": "5:00 p. m.",
        "label": "Ceremonia",
        "iconName": "Church"
      },
      {
        "time": "8:30 p. m.",
        "label": "Cena",
        "iconName": "Dinner"
      },
      {
        "time": "9:30 p. m.",
        "label": "Celebración",
        "iconName": "Party"
      }
    ]
  },
  "gallery": {
    "eyebrow": "Recuerdos",
    "title": "Romina",
    "subtitle": "Una historia entre naturaleza, familia y sueños",
    "items": [
      {
        "image": {
          "type": "uploaded",
          "assetId": "__ROMINA_ASSET_ID_portrait__",
          "src": "__ROMINA_ASSET_URL_portrait__"
        },
        "alt": "Retrato sonriente de Romina entre flores",
        "focalPointMobile": "50% 28%",
        "focalPointDesktop": "50% 24%"
      },
      {
        "image": {
          "type": "uploaded",
          "assetId": "__ROMINA_ASSET_ID_sageLandscape__",
          "src": "__ROMINA_ASSET_URL_sageLandscape__"
        },
        "alt": "Romina con vestido verde salvia en un jardín botánico",
        "focalPoint": "50% 45%"
      },
      {
        "image": {
          "type": "uploaded",
          "assetId": "__ROMINA_ASSET_ID_petPortrait__",
          "src": "__ROMINA_ASSET_URL_petPortrait__"
        },
        "alt": "Romina posa con una de sus mascotas",
        "focalPoint": "50% 30%"
      },
      {
        "image": {
          "type": "uploaded",
          "assetId": "__ROMINA_ASSET_ID_whitePortrait__",
          "src": "__ROMINA_ASSET_URL_whitePortrait__"
        },
        "alt": "Romina con vestido blanco en un entorno botánico",
        "focalPoint": "50% 30%"
      },
      {
        "image": {
          "type": "uploaded",
          "assetId": "__ROMINA_ASSET_ID_petLandscape__",
          "src": "__ROMINA_ASSET_URL_petLandscape__"
        },
        "alt": "Romina comparte un momento con sus mascotas en el jardín",
        "focalPoint": "50% 48%"
      },
      {
        "image": {
          "type": "uploaded",
          "assetId": "__ROMINA_ASSET_ID_whiteBotanical__",
          "src": "__ROMINA_ASSET_URL_whiteBotanical__"
        },
        "alt": "Romina con vestido blanco entre vegetación y cactus",
        "focalPoint": "50% 32%"
      },
      {
        "image": {
          "type": "uploaded",
          "assetId": "__ROMINA_ASSET_ID_social__",
          "src": "__ROMINA_ASSET_URL_social__"
        },
        "alt": "Romina con vestido verde salvia en una composición horizontal",
        "focalPoint": "50% 44%"
      },
      {
        "image": {
          "type": "uploaded",
          "assetId": "__ROMINA_ASSET_ID_pinkFloral__",
          "src": "__ROMINA_ASSET_URL_pinkFloral__"
        },
        "alt": "Romina con vestido rosa junto a una estructura floral",
        "focalPoint": "50% 28%"
      },
      {
        "image": {
          "type": "uploaded",
          "assetId": "__ROMINA_ASSET_ID_closing__",
          "src": "__ROMINA_ASSET_URL_closing__"
        },
        "alt": "Romina junto a globos con el número quince",
        "focalPoint": "50% 45%"
      }
    ]
  },
  "rsvp": {
    "title": "Confirme su asistencia",
    "subcopy": "Será muy especial contar con su presencia. Confirme su asistencia para ayudarnos a preparar cada detalle.",
    "guestCap": 4,
    "accessMode": "personalized-only",
    "confirmationMode": "api",
    "confirmationMessage": "Gracias por confirmar. Será un gusto compartir este día con usted.",
    "personalizedAccess": {
      "title": "Pase de acceso",
      "subtitle": "Esta invitación ha sido preparada especialmente para:",
      "footerText": "Favor de confirmar su asistencia en la siguiente sección."
    }
  },
  "thankYou": {
    "message": "Gracias por ser parte de este momento tan especial.",
    "closingName": "Romina",
    "date": "14 de agosto de 2026",
    "image": {
      "type": "uploaded",
      "assetId": "__ROMINA_ASSET_ID_closing__",
      "src": "__ROMINA_ASSET_URL_closing__"
    },
    "focalPoint": "50% 42%"
  },
  "sharing": {
    "ogImage": {
      "type": "uploaded",
      "assetId": "__ROMINA_ASSET_ID_social__",
      "src": "__ROMINA_ASSET_URL_social__"
    },
    "ogDescription": "Invitación a los XV años de Romina Ríos Chaparro",
    "whatsappTemplate": "Hola {name}, le compartimos su invitación para los XV años de Romina: {inviteUrl}"
  }
}
$romina_content$;
  v_storage_public_url text;
  v_asset_manifest jsonb := jsonb_build_object(
    'hero', 'Romina — portada',
    'portrait', 'Romina — retrato de presentación',
    'family', 'Romina — familia',
    'sageLandscape', 'Romina — vestido salvia horizontal',
    'social', 'Romina — vista previa social',
    'petPortrait', 'Romina — retrato con mascota',
    'petLandscape', 'Romina — mascotas',
    'whitePortrait', 'Romina — capítulo blanco',
    'whiteBotanical', 'Romina — retrato botánico',
    'pinkFloral', 'Romina — capítulo floral',
    'closing', 'Romina — cierre XV'
  );
  v_asset record;
  v_asset_id uuid;
  v_asset_url text;
BEGIN
  IF current_setting('app.owner_user_id', true) IN ('', '__OWNER_USER_ID__')
     OR current_setting('app.storage_public_url', true) IN ('', '__SUPABASE_PROJECT_URL__') THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: replace __OWNER_USER_ID__ and __SUPABASE_PROJECT_URL__ before execution.';
  END IF;
  v_owner_id := current_setting('app.owner_user_id')::uuid;
  v_storage_public_url := rtrim(current_setting('app.storage_public_url'), '/');

  SELECT id INTO v_invitation_id
  FROM public.invitations
  WHERE slug = 'romina-rios-chaparro' AND event_type = 'xv'
    AND archived_at IS NULL;
  IF v_invitation_id IS NULL THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: create the active Romina invitation and ingest its assets through the dashboard before this patch.';
  END IF;
  IF (SELECT count(*) FROM public.invitations WHERE slug = 'romina-rios-chaparro' AND event_type = 'xv') <> 1 THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: expected exactly one Romina invitation record.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = v_owner_id) THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: configured owner does not exist.';
  END IF;
  IF (
    SELECT count(*)
    FROM public.invitation_assets
    WHERE invitation_id = v_invitation_id
      AND display_name IN (SELECT value FROM jsonb_each_text(v_asset_manifest))
      AND deleted_at IS NULL
  ) <> jsonb_object_length(v_asset_manifest) THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: expected exactly % active canonical assets.', jsonb_object_length(v_asset_manifest);
  END IF;

  UPDATE public.invitations
  SET title = 'XV años de Romina Ríos Chaparro',
      status = 'published',
      base_demo_id = 'demo-xv-premiere-floral',
      theme_id = 'premiere-floral',
      kind = 'client',
      photos_received = true,
      created_by = v_owner_id
  WHERE id = v_invitation_id;

  FOR v_asset IN SELECT key, value FROM jsonb_each_text(v_asset_manifest) LOOP
    SELECT id, v_storage_public_url || '/storage/v1/object/public/' || bucket || '/' || storage_path
    INTO v_asset_id, v_asset_url
    FROM public.invitation_assets
    WHERE invitation_id = v_invitation_id
      AND display_name = v_asset.value
      AND deleted_at IS NULL;
    IF v_asset_id IS NULL THEN
      RAISE EXCEPTION 'PREFLIGHT_ABORT: missing active normalized asset %.', v_asset.value;
    END IF;
    v_content_text := replace(v_content_text, '__ROMINA_ASSET_ID_' || v_asset.key || '__', v_asset_id::text);
    v_content_text := replace(v_content_text, '__ROMINA_ASSET_URL_' || v_asset.key || '__', v_asset_url);
  END LOOP;
  IF v_content_text LIKE '%__ROMINA_ASSET_%__%' THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: unresolved asset placeholder remains.';
  END IF;
  v_content := v_content_text::jsonb;

  UPDATE public.published_invitation_content
  SET invitation_project_id = v_invitation_id, is_demo = false, content = v_content,
      published_at = now(), deleted_at = NULL
  WHERE slug = 'romina-rios-chaparro' AND event_type = 'xv';
  IF NOT FOUND THEN
    INSERT INTO public.published_invitation_content
      (invitation_project_id, slug, event_type, is_demo, content, version, published_at)
    VALUES (v_invitation_id, 'romina-rios-chaparro', 'xv', false, v_content, 1, now());
  END IF;

  SELECT id INTO v_event_id FROM public.events WHERE slug = 'romina-rios-chaparro' LIMIT 1;
  IF v_event_id IS NULL THEN
    INSERT INTO public.events
      (owner_user_id, invitation_project_id, slug, event_type, title, status, published_at)
    VALUES (v_owner_id, v_invitation_id, 'romina-rios-chaparro', 'xv', 'XV años de Romina Ríos Chaparro', 'published', now())
    RETURNING id INTO v_event_id;
  ELSE
    UPDATE public.events
    SET owner_user_id = v_owner_id, invitation_project_id = v_invitation_id,
        event_type = 'xv', title = 'XV años de Romina Ríos Chaparro',
        status = 'published', published_at = now(), deleted_at = NULL
    WHERE id = v_event_id;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.event_memberships
    WHERE event_id = v_event_id AND user_id = v_owner_id
      AND membership_role = 'owner' AND deleted_at IS NULL
  ) THEN
    INSERT INTO public.event_memberships (event_id, user_id, membership_role)
    VALUES (v_event_id, v_owner_id, 'owner');
  END IF;
END;
$romina$;

COMMIT;
