import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
	buildRominaPublishedContent,
	ROMINA_ASSET_SPECS,
	ROMINA_EVENT,
	type RominaAssetMap,
} from './romina-invitation-data';

export const ROMINA_SQL_PATCH_PATH =
	'scripts/manual/production-patches/20260716_prepare_romina_rios_chaparro_xv.sql';

function placeholderAssets(): RominaAssetMap {
	const assets = {} as RominaAssetMap;
	for (const asset of ROMINA_ASSET_SPECS) {
		assets[asset.key] = {
				type: 'uploaded' as const,
				assetId: `__ROMINA_ASSET_ID_${asset.key}__`,
				src: `__ROMINA_ASSET_URL_${asset.key}__`,
		};
	}
	return assets;
}

function sqlLiteral(value: string): string {
	return value.replace(/'/g, "''");
}

export function buildRominaInvitationSql(): string {
	const content = JSON.stringify(buildRominaPublishedContent(placeholderAssets()), null, 2);
	const assets = ROMINA_ASSET_SPECS.map(
		(asset) => `    '${asset.key}', '${sqlLiteral(asset.displayName)}'`,
	).join(',\n');

	return `-- ============================================================================
-- Romina Ríos Chaparro — XV invitation preparation patch
-- Generated by scripts/dev/generate-romina-invitation-sql.ts from the typed
-- canonical source scripts/dev/romina-invitation-data.ts. Do not hand-edit.
--
-- PENDING_DIRECT_CEREMONY_MAP_URL: current search URL is retained.
-- PENDING_DIRECT_RECEPTION_MAP_URL: current search URL is retained.
-- PENDING_RECEPTION_TIMELINE_CONFIRMATION: provisional itinerary is retained.
-- PENDING_MUSIC_AUDIO_ASSET, PENDING_RSVP_DEADLINE,
-- PENDING_RSVP_ACCESS_MODE_CONFIRMATION, PENDING_GUEST_LIST,
-- PENDING_DRESS_CODE, PENDING_GIFT_REGISTRY, PENDING_CHILDREN_POLICY,
-- PENDING_HASHTAG: optional fields are intentionally omitted.
-- PENDING_PRESENTATION_COPY and PENDING_CLOSING_COPY: provisional approved-safe
-- copy is retained in the canonical typed source.
--
-- REQUIRED BEFORE EXECUTION:
-- 1. Create this client invitation and upload the eleven canonical images via
--    the dashboard/asset workflow; this patch does not upload Storage objects.
-- 2. Replace __OWNER_USER_ID__ and __SUPABASE_PROJECT_URL__.
-- 3. Take a verified backup, validate this generated file, and obtain approval.
-- ============================================================================
-- @script-id: 20260716_prepare_romina_rios_chaparro_xv
-- @purpose: Prepare the published Romina Ríos Chaparro XV invitation from canonical typed content and existing normalized Storage assets
-- @env: production
-- @ticket: Romina invitation preparation; source scripts/dev/romina-invitation-data.ts
-- @tables: public.invitations, public.invitation_assets, public.published_invitation_content, public.events, public.event_memberships
-- @operation: update
-- @expected-rows-min: 1
-- @expected-rows-max: 5
-- @requires-backup: true
-- @dry-run-query: SELECT id, slug, event_type, status, base_demo_id, theme_id, archived_at FROM public.invitations WHERE slug = 'romina-rios-chaparro' AND event_type = 'xv'; SELECT id, display_name, bucket, storage_path, deleted_at FROM public.invitation_assets WHERE invitation_id = (SELECT id FROM public.invitations WHERE slug = 'romina-rios-chaparro' AND event_type = 'xv' AND archived_at IS NULL); SELECT id, slug, event_type, version, published_at, deleted_at FROM public.published_invitation_content WHERE slug = 'romina-rios-chaparro' AND event_type = 'xv'; SELECT id, slug, event_type, status, invitation_project_id, deleted_at FROM public.events WHERE slug = 'romina-rios-chaparro';
-- @rollback: Restore the verified backup or archive the invitation through the approved application workflow; never delete guest or Storage history manually.

BEGIN;

SELECT set_config('app.owner_user_id', '__OWNER_USER_ID__', true);
SELECT set_config('app.storage_public_url', '__SUPABASE_PROJECT_URL__', true);

DO $romina$
DECLARE
  v_invitation_id uuid;
  v_owner_id uuid;
  v_event_id uuid;
  v_content jsonb;
  v_content_text text := $romina_content$
${content}
$romina_content$;
  v_storage_public_url text;
  v_asset_manifest jsonb := jsonb_build_object(
${assets}
  );
  v_asset record;
  v_asset_id uuid;
  v_asset_url text;
BEGIN
  IF current_setting('app.owner_user_id', true) IN ('', '__OWNER_USER_ID__')
     OR current_setting('app.storage_public_url', true) IN ('', '__SUPABASE_PROJECT_URL__') THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: replace __OWNER_USER_ID__ and __SUPABASE_PROJECT_URL__ before execution.';
  END IF;
  v_owner_id := current_setting('app.owner_user_id')::uuid;
  v_storage_public_url := rtrim(current_setting('app.storage_public_url'), '/');

  SELECT id INTO v_invitation_id
  FROM public.invitations
  WHERE slug = '${ROMINA_EVENT.slug}' AND event_type = '${ROMINA_EVENT.eventType}'
    AND archived_at IS NULL;
  IF v_invitation_id IS NULL THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: create the active Romina invitation and ingest its assets through the dashboard before this patch.';
  END IF;
  IF (SELECT count(*) FROM public.invitations WHERE slug = '${ROMINA_EVENT.slug}' AND event_type = '${ROMINA_EVENT.eventType}') <> 1 THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: expected exactly one Romina invitation record.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = v_owner_id) THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: configured owner does not exist.';
  END IF;
  IF (
    SELECT count(*)
    FROM public.invitation_assets
    WHERE invitation_id = v_invitation_id
      AND display_name IN (SELECT value FROM jsonb_each_text(v_asset_manifest))
      AND deleted_at IS NULL
  ) <> jsonb_object_length(v_asset_manifest) THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: expected exactly % active canonical assets.', jsonb_object_length(v_asset_manifest);
  END IF;

  UPDATE public.invitations
  SET title = '${sqlLiteral(ROMINA_EVENT.title)}',
      status = 'published',
      base_demo_id = '${ROMINA_EVENT.baseDemoId}',
      theme_id = '${ROMINA_EVENT.themeId}',
      kind = 'client',
      photos_received = true,
      created_by = v_owner_id
  WHERE id = v_invitation_id;

  FOR v_asset IN SELECT key, value FROM jsonb_each_text(v_asset_manifest) LOOP
    SELECT id, v_storage_public_url || '/storage/v1/object/public/' || bucket || '/' || storage_path
    INTO v_asset_id, v_asset_url
    FROM public.invitation_assets
    WHERE invitation_id = v_invitation_id
      AND display_name = v_asset.value
      AND deleted_at IS NULL;
    IF v_asset_id IS NULL THEN
      RAISE EXCEPTION 'PREFLIGHT_ABORT: missing active normalized asset %.', v_asset.value;
    END IF;
    v_content_text := replace(v_content_text, '__ROMINA_ASSET_ID_' || v_asset.key || '__', v_asset_id::text);
    v_content_text := replace(v_content_text, '__ROMINA_ASSET_URL_' || v_asset.key || '__', v_asset_url);
  END LOOP;
  IF v_content_text LIKE '%__ROMINA_ASSET_%__%' THEN
    RAISE EXCEPTION 'PREFLIGHT_ABORT: unresolved asset placeholder remains.';
  END IF;
  v_content := v_content_text::jsonb;

  UPDATE public.published_invitation_content
  SET invitation_project_id = v_invitation_id, is_demo = false, content = v_content,
      published_at = now(), deleted_at = NULL
  WHERE slug = '${ROMINA_EVENT.slug}' AND event_type = '${ROMINA_EVENT.eventType}';
  IF NOT FOUND THEN
    INSERT INTO public.published_invitation_content
      (invitation_project_id, slug, event_type, is_demo, content, version, published_at)
    VALUES (v_invitation_id, '${ROMINA_EVENT.slug}', '${ROMINA_EVENT.eventType}', false, v_content, 1, now());
  END IF;

  SELECT id INTO v_event_id FROM public.events WHERE slug = '${ROMINA_EVENT.slug}' LIMIT 1;
  IF v_event_id IS NULL THEN
    INSERT INTO public.events
      (owner_user_id, invitation_project_id, slug, event_type, title, status, published_at)
    VALUES (v_owner_id, v_invitation_id, '${ROMINA_EVENT.slug}', '${ROMINA_EVENT.eventType}', '${sqlLiteral(ROMINA_EVENT.title)}', 'published', now())
    RETURNING id INTO v_event_id;
  ELSE
    UPDATE public.events
    SET owner_user_id = v_owner_id, invitation_project_id = v_invitation_id,
        event_type = '${ROMINA_EVENT.eventType}', title = '${sqlLiteral(ROMINA_EVENT.title)}',
        status = 'published', published_at = now(), deleted_at = NULL
    WHERE id = v_event_id;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.event_memberships
    WHERE event_id = v_event_id AND user_id = v_owner_id
      AND membership_role = 'owner' AND deleted_at IS NULL
  ) THEN
    INSERT INTO public.event_memberships (event_id, user_id, membership_role)
    VALUES (v_event_id, v_owner_id, 'owner');
  END IF;
END;
$romina$;

COMMIT;
`;
}

function main(): void {
	const destination = resolve(process.cwd(), ROMINA_SQL_PATCH_PATH);
	const sql = buildRominaInvitationSql();
	if (process.argv.includes('--check')) {
		if (readFileSync(destination, 'utf8') !== sql) {
			throw new Error(`Generated SQL is stale: run tsx scripts/dev/generate-romina-invitation-sql.ts`);
		}
		return;
	}
	writeFileSync(destination, sql);
}

if (process.argv[1]?.endsWith('generate-romina-invitation-sql.ts')) main();
