-- Valentina Memories guest ownership, moderation state, and organizer audit.
--
-- Objects remain in private R2. These tables contain only non-PII media
-- metadata and opaque session identifiers. All application access is through
-- server routes using service-role PostgREST after an auth decision.

begin;

create table if not exists public.valentina_memory_sessions (
	 id uuid primary key default gen_random_uuid(),
	 event_key text not null,
	 token_hash text not null unique,
	 recovery_code_hash text not null unique,
	 created_at timestamptz not null default now(),
	 last_seen_at timestamptz not null default now(),
	 expires_at timestamptz not null,
	 revoked_at timestamptz
);

create index if not exists idx_valentina_memory_sessions_active
	on public.valentina_memory_sessions (event_key, expires_at)
	where revoked_at is null;

create table if not exists public.valentina_memory_items (
	 id uuid primary key default gen_random_uuid(),
	 event_key text not null,
	 session_id uuid not null references public.valentina_memory_sessions(id) on delete cascade,
	 object_key text not null unique,
	 mime_type text not null,
	 size_bytes bigint not null check (size_bytes > 0),
	 duration_seconds numeric(10, 3),
	 caption text not null default '',
	 status text not null default 'uploading' check (status in ('uploading', 'validating', 'accepted', 'rejected', 'deleted')),
	 created_at timestamptz not null default now(),
	 updated_at timestamptz not null default now(),
	 accepted_at timestamptz,
	 rejected_at timestamptz,
	 deleted_at timestamptz
);

create index if not exists idx_valentina_memory_items_session
	on public.valentina_memory_items (session_id, created_at desc);

create index if not exists idx_valentina_memory_items_event_status
	on public.valentina_memory_items (event_key, status, created_at desc);

create table if not exists public.valentina_memory_audit_events (
	 id bigint generated by default as identity primary key,
	 event_key text not null,
	 media_item_id uuid references public.valentina_memory_items(id) on delete set null,
	 actor_type text not null check (actor_type in ('guest', 'organizer', 'system')),
	 actor_id text,
	 action text not null,
	metadata jsonb not null default '{}'::jsonb,
	created_at timestamptz not null default now(),
	expires_at timestamptz not null
);

create index if not exists idx_valentina_memory_audit_events_media
	on public.valentina_memory_audit_events (event_key, media_item_id, created_at desc);

alter table public.valentina_memory_sessions enable row level security;
alter table public.valentina_memory_items enable row level security;
alter table public.valentina_memory_audit_events enable row level security;

drop policy if exists "service role valentina memory sessions" on public.valentina_memory_sessions;
create policy "service role valentina memory sessions"
	on public.valentina_memory_sessions
	for all to service_role using (true) with check (true);

drop policy if exists "service role valentina memory items" on public.valentina_memory_items;
create policy "service role valentina memory items"
	on public.valentina_memory_items
	for all to service_role using (true) with check (true);

drop policy if exists "service role valentina memory audit" on public.valentina_memory_audit_events;
create policy "service role valentina memory audit"
	on public.valentina_memory_audit_events
	for all to service_role using (true) with check (true);

commit;
