import type { CanonicalStatusView } from '@/lib/status/types';

export function buildCanonicalStatusViewFixture(
	overrides: Partial<CanonicalStatusView> = {},
): CanonicalStatusView {
	const env = (environment: 'local' | 'preview' | 'production') => ({
		environment,
		schemaLifecycle: 'CURRENT' as const,
		appliedCount: 75,
		expectedCount: 75,
		migrationHead: '20260806120000',
		pendingMigrations: [],
		extraMigrations: [],
		invitationAttentionCount: 1,
		identityConflictsCount: 0,
		targetClassification: environment === 'local' ? 'persistent-local' : environment,
		environmentIdentityOk: true,
		schemaOperationReadiness: 'NEEDS_DISPOSABLE_PROOF' as const,
		schemaNextAction: 'pnpm db:migrate -- --target disposable-test --apply',
		authorizationIntegrity:
			environment === 'production' ? ('GRANDFATHERED' as const) : ('NOT_APPLICABLE' as const),
		authorizationMissingVersions: [],
		evidence: 'LIVE' as const,
		probedAt: '2026-08-12T22:11:46.000Z',
	});
	return {
		schemaVersion: 2,
		generatedAt: '2026-08-12T22:11:54.000Z',
		evidence: 'LIVE',
		expectedMigrationHead: '20260806120000',
		expectedMigrationCount: 75,
		registryCount: 5,
		inSyncCount: 0,
		inSyncSlugs: [],
		environments: {
			local: env('local'),
			preview: env('preview'),
			production: env('production'),
		},
		disposableProof: {
			status: 'missing',
			reason: 'Missing disposable migration proof.',
			evidence: 'LIVE',
		},
		promotions: [
			{
				slug: 'victoria-y-roberto',
				title: 'Boda de Victoria y Roberto',
				eventType: 'boda',
				action: 'PROMOTE_PRODUCTION',
				reasonCode: 'PREVIEW_ALIGNED_PRODUCTION_BEHIND',
				environments: { local: 'match', preview: 'match', production: 'behind' },
				source: 'preview',
				destination: 'production',
				evidence: 'LIVE',
				envEvidence: { local: 'LIVE', preview: 'LIVE', production: 'LIVE' },
				uncertaintyNotes: [],
				handoff: {
					dryRunCommand: null,
					applyCommand: 'pnpm prod:apply -- --slug victoria-y-roberto --apply',
					ownerApplyRequired: true,
					optionalDiagnosticCommand: null,
					steps: ['OWNER APPLY in TTY (CLI runs preflight and release-check)'],
					dryRunStepType: 'Apply',
					applyStepType: 'Apply',
				},
			},
		],
		activeRowCounts: { local: 26, preview: 27, production: 26 },
		identityConflictCounts: { local: 0, preview: 0, production: 0 },
		manualPatches: [
			{
				scriptId: '20260812_p0_itinerary_gallery_structural_contracts',
				file: 'scripts/manual/production-patches/20260812_p0_itinerary_gallery_structural_contracts.sql',
				purpose:
					'Persist itinerary timeline-paper and celestial gallery structural contracts.',
				targetEnvironments: ['production'],
				expectedRowsMin: 4,
				expectedRowsMax: 8,
				environments: {
					local: {
						status: 'NOT_APPLICABLE',
						evidence: 'LIVE',
						matchingRowCount: null,
						verifiedAt: null,
						reason: 'ENVIRONMENT_NOT_TARGET',
						planCommand: null,
					},
					preview: {
						status: 'NOT_APPLICABLE',
						evidence: 'LIVE',
						matchingRowCount: null,
						verifiedAt: null,
						reason: 'ENVIRONMENT_NOT_TARGET',
						planCommand: null,
					},
					production: {
						status: 'PENDING',
						evidence: 'LIVE',
						matchingRowCount: 4,
						verifiedAt: '2026-08-12T22:11:46.000Z',
						reason: 'LIVE_ROWS_WITHIN_RANGE',
						planCommand: 'pnpm prod:apply -- --patch <file>',
					},
				},
			},
			{
				scriptId: '20260812_thankyou_editorial_back_cover_structural_contracts',
				file: 'scripts/manual/production-patches/20260812_thankyou_editorial_back_cover_structural_contracts.sql',
				purpose: 'Persist thank-you editorial back-cover structural contracts.',
				targetEnvironments: ['production'],
				expectedRowsMin: 5,
				expectedRowsMax: 10,
				environments: {
					local: {
						status: 'NOT_APPLICABLE',
						evidence: 'LIVE',
						matchingRowCount: null,
						verifiedAt: null,
						reason: 'ENVIRONMENT_NOT_TARGET',
						planCommand: null,
					},
					preview: {
						status: 'NOT_APPLICABLE',
						evidence: 'LIVE',
						matchingRowCount: null,
						verifiedAt: null,
						reason: 'ENVIRONMENT_NOT_TARGET',
						planCommand: null,
					},
					production: {
						status: 'NOT_NEEDED',
						evidence: 'LIVE',
						matchingRowCount: 0,
						verifiedAt: '2026-08-12T22:11:46.000Z',
						reason: 'LIVE_ZERO_ROWS',
						planCommand: null,
					},
				},
			},
		],
		diagnostics: [],
		...overrides,
	};
}
